CREATE DATABASE IF NOT EXISTS orbtasoft CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE orbtasoft;

CREATE TABLE IF NOT EXISTS contact_messages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
